### PR TITLE
enable ConnectionString usage in pg client

### PR DESCRIPTION
**Pull request by twhitbeck**
## Is this a breaking change?

- [ ] Yes
- [x] No

## Checklist:

Please review the
[guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md)
to this repository.

- [x] Updated JSDoc (for methods changed/added)
- [x] Added tests to cover added functionalities.
- [x] Updated readme (if applicable).
- [x] Added/updated examples in example folder.
- [x] Make sure the pipeline passes.

When all of the above is completed, request a review from one of the codeowners.

## Description:

Support all constructor parameter patterns of `deno-postgres` client.

### CODE REVIEW

**Comment by twhitbeck** [comment]
@halvardssm looks like the checks are passing. would you mind reviewing this? Thanks!

(some context: I'm using `fly.io` postgres instances which supply only a connection string, so I need to be able to instantiate my postgres client instance with just a connection string)

**Comment by halvardssm** [comment]
Hi @twhitbeck ! Thanks for your PR! I have no problem with merging this change, but could you add the same type for the MySQL and SQLite clients as well?

**Comment by twhitbeck** [comment]
> Hi @twhitbeck ! Thanks for your PR! I have no problem with merging this change, but could you add the same type for the MySQL and SQLite clients as well?

Looks like the MySQL client is fine as is. I applied the same approach to the SQLite client, though.

**Review by halvardssm — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
