### PR TITLE
Fix the experimental tests and make sure experimental mode is working

### LINKED ISSUE #93: [BUG] Expermental Mode never populates nessie_migrations table
**System (please complete the following information):**
 - OS: linux
 - Deno version 1.7.2
 - Nessie version 1.1.3

**Describe the bug**
When a migration is run with experimental mode turned on the nessie_migrations table never gets populated.

I took a look at the code in AbstractClient.ts and it seems that if experimental mode is enabled it will never get to QUERY_MIGRATION_INSERT because thats behind the `else` on line 223.

**To Reproduce**
1. Run a migration with experimental mode on
2. Check nessie_migrations table

**Expected behavior**
nessie_migrations table should have values in it.

### PR DESCRIPTION
**Pull request by Teddy-Schmitz**
Fixes #93 

## Is this a breaking change?

- [ ] Yes
- [x] No

## Checklist:

Please review the [guidelines for contributing](https://github.com/halvardssm/deno-nessie/blob/master/.github/CONTRIBUTING.md) to this repository.

- [ ] Updated JSDoc (for methods changed/added)
- [x] Added tests to cover added functionalities.
- [ ] Updated readme (if applicable).
- [ ] Added/updated examples in example folder.
- [ ] Make sure the pipeline passes.

When all of the above is completed, request a review from one of the codeowners.

## Description:

I discovered a few issues unrelated to the original bug report.  It looks like tests were never running on the experimental code as the config in the experimental folder was pointing to the regular `cli` folder.  I fixed this and then noticed that seeding functionality was never ported over to experimental mode so I fixed that as well.

### CODE REVIEW

**Comment by Teddy-Schmitz** [comment]
Not sure why tests are failing I didnt change how things connect for tests.  Works fine locally

**Comment by halvardssm** [comment]
It seems like there is something wrong with the database services used in the ci. I will take a look at it and see if anything got updated with github ci since last release.

**Review by halvardssm — APPROVED** [review]
It looks good to me! Just need to figure out why the db connection is failing so that we can merge

**Comment by Teddy-Schmitz** [comment]
Are you able to restart the jobs?  I dont see a button to retry without having to push something.

**Comment by halvardssm** [comment]
I have tried to figure out why this would not be working, but my best guess at this point is that there is something wrong with deno on the github runner. I have tested it locally, so I will merge this story in now, but wait with updating the version until I have found a workaround. Thank you so much for your work!

**Pull request merged**
